<?php
	///init site configurations
	define('VERSION', '{{VERSION}}');
	define('DEBUG', '{{DEBUG}}');
	define('INSTALL', '{{INSTALL}}');
	//site configurations
	define('FORCE_SSL', '{{FORCE_SSL}}');
	define('ALLOW_ORIGINS', '{{ALLOW_ORIGINS}}');
	define('SITE', '{{SITE}}');
	define('SITE_ID', '{{SITE_ID}}');
	define('SITE_MODE', '{{SITE_MODE}}');
	define('SITE_LAYOUT', '{{SITE_LAYOUT}}');
	define('SITE_ROOT', '{{SITE_ROOT}}');
	define('HOMELABEL', '{{HOMELABEL}}');
	define('USER_ADMIN', '{{USER_ADMIN}}');
	define('DESC', '{{DESC}}');
	define('ABOUT', '{{ABOUT}}');
	define('MINIDESC', '{{MINIDESC}}');
	define('ABOUTIMG', '{{ABOUTIMG}}');
	define('ABOUTVIDEO', '{{ABOUTVIDEO}}');
	define('ABOUTLABEL', '{{ABOUTLABEL}}');
	define('CONTAINER_LAYOUT', '{{CONTAINER_LAYOUT}}');
	define('LANG', '{{LANG}}');
	//db config
	define('DB_DRIVER', '{{DB_DRIVER}}');
	define('DB_host', '{{DB_host}}');
	define('DB_name', '{{DB_name}}');
	define('DB_user', '{{DB_user}}');
	define('DB_password', '{{DB_password}}');
	//Look and feel
	define('LFColor', '{{LFColor}}');
	define('LFBKColor', '{{LFBKColor}}');
	define('LFFont', '{{LFFont}}');//Open Sans|Abril Fatface|Josefin Slab|Sedgwick Ave|Acme|Anton|Arvo|Dancing Script|Lato|Lora|Merriweather|Pacifico|Questrial|Saira Extra Condensed|Sedgwick Ave Display|Shadows Into Light|Quicksand|Skranji
	define('LFFontColor', '{{LFFontColor}}');
	define('LandingColor', '{{LandingColor}}');
	define('AboutColor', '{{AboutColor}}');
	define('LFfavicon', '{{LFfavicon}}');
	define('LFLogo', '{{LFLogo}}');
	define('LFParallax', '{{LFParallax}}');
	define('LandingVideo', '{{LandingVideo}}');
	define('ANIME_ON', '{{ANIME_ON}}');
	define('SIDENAV', '{{SIDENAV}}');
	define('SIDENAVPOS', '{{SIDENAVPOS}}');
	define('SIDENAVPOS_Y', '{{SIDENAVPOS_Y}}');
	define('NAVBAR', '{{NAVBAR}}');
	//internal api
	define('APIKEY', '{{APIKEY}}');
	//crypto keys
	define('SECRET_SHARE', '{{SECRET_SHARE}}');
	define('SECRET_PUBLIC', '{{SECRET_PUBLIC}}');
	//twitch api
	define('TWITCH_CLIENT', '{{TWITCH_CLIENT}}');
	define('TWITCH_SECRET', '{{TWITCH_SECRET}}');
